import 'dart:io';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import 'date_formatter.dart';

class PrintUtils {
  const PrintUtils._();

  static const _line = '──────────────────────────────────';
  static const _dotLine = '──────────────────────────────────';

  static final NumberFormat _twoDecimal = NumberFormat.currency(
    decimalDigits: 2,
    symbol: '',
  );

  static String _pad(String value, int width, {bool right = false}) {
    final padded = value.padRight(width);
    return right ? padded.substring(0, width) : padded;
  }

  static String _center(String value, int width) {
    if (value.length >= width) return value.substring(0, width);
    final left = (width - value.length) ~/ 2;
    final right = width - value.length - left;
    return ' ' * left + value + ' ' * right;
  }

  static String generateReceiptText({
    required String businessName,
    String? businessAddress,
    String? businessPhone,
    required String receiptNumber,
    required DateTime dateTime,
    required List<ReceiptItem> items,
    required double subtotal,
    required double total,
    required String paymentMethod,
    String? customerName,
    String? customerPhone,
    String? footerMessage,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(_center(businessName, 36));
    if (businessAddress != null && businessAddress.isNotEmpty) {
      buffer.writeln(_center(businessAddress, 36));
    }
    if (businessPhone != null && businessPhone.isNotEmpty) {
      buffer.writeln(_center('Tel: $businessPhone', 36));
    }
    buffer.writeln();
    buffer.writeln(_line);
    buffer.writeln('Receipt #: ${_pad(receiptNumber, 36)}');
    buffer.writeln('Date: ${DateFormatter.formatDateTime(dateTime)}');
    buffer.writeln(_line);
    buffer.writeln(
      '${_pad('Item', 18)} ${_pad('Qty', 5)} ${_pad('Price', 10)} ${_pad('Total', 8)}',
    );
    buffer.writeln(_dotLine);

    for (final item in items) {
      final name = item.name.length > 18 ? item.name.substring(0, 18) : item.name;
      final qty = item.quantity.toString();
      final price = _twoDecimal.format(item.unitPrice);
      final lineTotal = _twoDecimal.format(item.unitPrice * item.quantity);
      buffer.writeln(
        '${_pad(name, 18)} ${_pad(qty, 5)} ${_pad(price, 10)} ${_pad(lineTotal, 8)}',
      );
    }

    buffer.writeln(_line);
    buffer.writeln(
      '${_pad('Subtotal', 26)} ${_pad(_twoDecimal.format(subtotal), 10)}',
    );
    buffer.writeln(
      '${_pad('TOTAL', 26)} ${_pad(_twoDecimal.format(total), 10)}',
    );
    buffer.writeln(_line);
    buffer.writeln('Payment: $paymentMethod');
    if (customerName != null && customerName.isNotEmpty) {
      buffer.writeln('Customer: $customerName');
    }
    if (customerPhone != null && customerPhone.isNotEmpty) {
      buffer.writeln('Phone: $customerPhone');
    }
    buffer.writeln(_line);
    if (footerMessage != null && footerMessage.isNotEmpty) {
      buffer.writeln(_center(footerMessage, 36));
    }
    buffer.writeln(_center('Thank you!', 36));

    return buffer.toString();
  }

  static String generateCashReportText({
    required String businessName,
    required String asOf,
    required double total,
    required List<CashAccount> accounts,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(_center(businessName, 36));
    buffer.writeln(_center('CASH POSITION REPORT', 36));
    buffer.writeln();
    buffer.writeln('As of: $asOf');
    buffer.writeln(_line);
    buffer.writeln(
      '${_pad('Account', 20)} ${_pad('Type', 12)} ${_pad('Balance', 8)}',
    );
    buffer.writeln(_dotLine);

    for (final account in accounts) {
      final name = account.name.length > 20 ? account.name.substring(0, 20) : account.name;
      final subtype = account.subtype.length > 12 ? account.subtype.substring(0, 12) : account.subtype;
      final balance = _twoDecimal.format(account.balance);
      buffer.writeln(
        '${_pad(name, 20)} ${_pad(subtype, 12)} ${_pad(balance, 8)}',
      );
    }

    buffer.writeln(_line);
    buffer.writeln(
      '${_pad('TOTAL', 32)} ${_pad(_twoDecimal.format(total), 8)}',
    );
    buffer.writeln(_line);
    buffer.writeln(_center('Generated by FinMind', 36));

    return buffer.toString();
  }

  static String generateProfitLossReportText({
    required String businessName,
    required String periodFrom,
    required String periodTo,
    required double revenue,
    required double cogs,
    required double grossProfit,
    required double expenses,
    required double netProfit,
    required List<ExpenseBreakdownItem> expenseBreakdown,
  }) {
    final buffer = StringBuffer();

    buffer.writeln(_center(businessName, 36));
    buffer.writeln(_center('PROFIT & LOSS REPORT', 36));
    buffer.writeln();
    buffer.writeln('Period: $periodFrom to $periodTo');
    buffer.writeln(_line);
    buffer.writeln('INCOME');
    buffer.writeln(
      '${_pad('Revenue', 28)} ${_pad(_twoDecimal.format(revenue), 10)}',
    );
    buffer.writeln();
    buffer.writeln('COST OF GOODS SOLD');
    buffer.writeln(
      '${_pad('COGS', 28)} ${_pad(_twoDecimal.format(cogs), 10)}',
    );
    buffer.writeln();
    buffer.writeln(
      '${_pad('GROSS PROFIT', 28)} ${_pad(_twoDecimal.format(grossProfit), 10)}',
    );
    buffer.writeln();
    buffer.writeln('EXPENSES');
    for (final item in expenseBreakdown) {
      final category = item.category.length > 14 ? item.category.substring(0, 14) : item.category;
      final name = item.name.length > 14 ? item.name.substring(0, 14) : item.name;
      buffer.writeln(
        '  ${_pad(category, 14)} ${_pad(name, 14)} ${_pad(_twoDecimal.format(item.amount), 10)}',
      );
    }
    buffer.writeln(
      '${_pad('Total Expenses', 28)} ${_pad(_twoDecimal.format(expenses), 10)}',
    );
    buffer.writeln(_line);
    buffer.writeln(
      '${_pad('NET PROFIT', 28)} ${_pad(_twoDecimal.format(netProfit), 10)}',
    );
    buffer.writeln(_line);
    buffer.writeln(_center('Generated by FinMind', 36));

    return buffer.toString();
  }

  static Future<void> printReceipt({
    required String businessName,
    String? businessAddress,
    String? businessPhone,
    required String receiptNumber,
    required DateTime dateTime,
    required List<ReceiptItem> items,
    required double subtotal,
    required double total,
    required String paymentMethod,
    String? customerName,
    String? customerPhone,
    String? footerMessage,
  }) async {
    final text = generateReceiptText(
      businessName: businessName,
      businessAddress: businessAddress,
      businessPhone: businessPhone,
      receiptNumber: receiptNumber,
      dateTime: dateTime,
      items: items,
      subtotal: subtotal,
      total: total,
      paymentMethod: paymentMethod,
      customerName: customerName,
      customerPhone: customerPhone,
      footerMessage: footerMessage,
    );

    await _sharePdf(text, 'Receipt $receiptNumber');
  }

  static Future<void> printCashReport({
    required String businessName,
    required String asOf,
    required double total,
    required List<CashAccount> accounts,
  }) async {
    final text = generateCashReportText(
      businessName: businessName,
      asOf: asOf,
      total: total,
      accounts: accounts,
    );

    await _sharePdf(text, 'Cash Position Report');
  }

  static Future<void> printProfitLossReport({
    required String businessName,
    required String periodFrom,
    required String periodTo,
    required double revenue,
    required double cogs,
    required double grossProfit,
    required double expenses,
    required double netProfit,
    required List<ExpenseBreakdownItem> expenseBreakdown,
  }) async {
    final text = generateProfitLossReportText(
      businessName: businessName,
      periodFrom: periodFrom,
      periodTo: periodTo,
      revenue: revenue,
      cogs: cogs,
      grossProfit: grossProfit,
      expenses: expenses,
      netProfit: netProfit,
      expenseBreakdown: expenseBreakdown,
    );

    await _sharePdf(text, 'Profit & Loss Report');
  }

  static Future<void> shareReceipt({
    required String businessName,
    String? businessAddress,
    String? businessPhone,
    required String receiptNumber,
    required DateTime dateTime,
    required List<ReceiptItem> items,
    required double subtotal,
    required double total,
    required String paymentMethod,
    String? customerName,
    String? customerPhone,
    String? footerMessage,
  }) async {
    final text = generateReceiptText(
      businessName: businessName,
      businessAddress: businessAddress,
      businessPhone: businessPhone,
      receiptNumber: receiptNumber,
      dateTime: dateTime,
      items: items,
      subtotal: subtotal,
      total: total,
      paymentMethod: paymentMethod,
      customerName: customerName,
      customerPhone: customerPhone,
      footerMessage: footerMessage,
    );

    await Share.share(text, subject: 'Receipt $receiptNumber');
  }

  static Future<void> shareCashReport({
    required String businessName,
    required String asOf,
    required double total,
    required List<CashAccount> accounts,
  }) async {
    final text = generateCashReportText(
      businessName: businessName,
      asOf: asOf,
      total: total,
      accounts: accounts,
    );

    await Share.share(text, subject: 'Cash Position Report');
  }

  static Future<void> shareProfitLossReport({
    required String businessName,
    required String periodFrom,
    required String periodTo,
    required double revenue,
    required double cogs,
    required double grossProfit,
    required double expenses,
    required double netProfit,
    required List<ExpenseBreakdownItem> expenseBreakdown,
  }) async {
    final text = generateProfitLossReportText(
      businessName: businessName,
      periodFrom: periodFrom,
      periodTo: periodTo,
      revenue: revenue,
      cogs: cogs,
      grossProfit: grossProfit,
      expenses: expenses,
      netProfit: netProfit,
      expenseBreakdown: expenseBreakdown,
    );

    await Share.share(text, subject: 'Profit & Loss Report');
  }

  static Future<void> _sharePdf(String text, String jobName) async {
    final pdfDoc = pw.Document();

    pdfDoc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat(80 * PdfPageFormat.mm, 500 * PdfPageFormat.mm),
        build: (context) {
          final lines = text.split('\n');
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.stretch,
            children: [
              for (final line in lines)
                pw.Text(line, style: const pw.TextStyle(fontSize: 10)),
            ],
          );
        },
      ),
    );

    final tempDir = await getTemporaryDirectory();
    final file = File('${tempDir.path}/$jobName.pdf');
    await file.writeAsBytes(await pdfDoc.save());

    await Share.shareXFiles([XFile(file.path)], text: jobName);
  }
}

class PrintException implements Exception {
  const PrintException(this.message);

  final String message;

  @override
  String toString() => 'PrintException: $message';
}

class ReceiptItem {
  const ReceiptItem({
    required this.name,
    required this.quantity,
    required this.unitPrice,
  });

  final String name;
  final int quantity;
  final double unitPrice;
}

class CashAccount {
  const CashAccount({
    required this.subtype,
    required this.name,
    required this.balance,
  });

  final String subtype;
  final String name;
  final double balance;
}

class ExpenseBreakdownItem {
  const ExpenseBreakdownItem({
    required this.category,
    required this.name,
    required this.amount,
  });

  final String category;
  final String name;
  final double amount;
}
